ajou:
  google:
    registration-id: google
    token-endpoint: https://oauth2.googleapis.com/token
    calendar-api-url: https://www.googleapis.com/calendar/v3/calendars/{calendarId}/events
    people-api-url: https://people.googleapis.com/v1/people/me?personFields=organizations
