spring:
  application:
    name: ajouevent-be-v2
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:prod}
  config:
    import:
      - classpath:config/db.yaml
      - classpath:config/oauth.yaml
      - classpath:config/jwt.yaml
      - classpath:config/fcm.yaml
      - classpath:config/discord.yaml
      - classpath:config/aws.yaml
      - classpath:config/google.yaml

ajou:
  swagger:
    server-url: ${SWAGGER_SERVER_URL:http://localhost:8080}
