spring:
  jpa:
    hibernate:
      ddl-auto: create
    defer-datasource-initialization: true
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  sql:
    init:
      mode: always

ajou:
  swagger:
    server-url: http://localhost:8080
  fcm:
    executor:
      callback:
        core-pool-size: 8
        max-pool-size: 32
        queue-capacity: 500
        await-termination-seconds: 30
      default-pool:
        core-pool-size: 32
        max-pool-size: 128
        queue-capacity: 50000

jwt:
  cookie-secure: false
