INSERT INTO topics (id, classification, department, korean_order, korean_topic, type) VALUES
(1, '학과', 'AIMobilityEngineering', 23, '미래모빌리티공학과', 'AIMOBILITYENGINEERING'),
(2, '공지사항', 'AjouNormal', 36, '아주대학교-일반', 'AJOUNORMAL'),
(3, '공지사항', 'AjouScholarship', 37, '아주대학교-장학', 'AJOUSCHOLARSHIP'),
(4, '학과', 'AppliedArtificialIntelligence', 44, '인공지능융합학과', 'APPLIEDARTIFICIALINTELLIGENCE'),
(5, '학과', 'AppliedChemistryBiologicalEngineering', 42, '응용화학생명공학과', 'APPLIEDCHEMISTRYBIOLOGICALENGINEERING'),
(6, '학과', 'Architecture', 3, '건축학과', 'ARCHITECTURE'),
(7, '학과', 'BiologicalScience', 30, '생명과학과', 'BIOLOGICALSCIENCE'),
(8, '단과대', 'Business', 4, '경영대학', 'BUSINESS'),
(9, '학과', 'BusinessAdministration', 6, '경영학과', 'BUSINESSADMINISTRATION'),
(10, '학과', 'ChemicalEngineering', 56, '화학공학과', 'CHEMICALENGINEERING'),
(11, '학과', 'Chemistry', 57, '화학과', 'CHEMISTRY'),
(12, '학과', 'CivilSystemsEngineering', 2, '건설시스템공학과', 'CIVILSYSTEMSENGINEERING'),
(13, '단과대', 'ComputingInformatics', 31, '소프트웨어융합대학', 'COMPUTINGINFORMATICS'),
(14, '학과', 'CultureContents', 21, '문화콘텐츠학과', 'CULTURECONTENTS'),
(15, '학과', 'CyberSecurity', 25, '사이버보안학과', 'CYBERSECURITY'),
(16, '단과대', 'Dasan', 18, '다산학부대학', 'DASAN'),
(17, '학과', 'DigitalMedia', 20, '디지털미디어학과', 'DIGITALMEDIA'),
(18, '학과', 'Economics', 8, '경제학과', 'ECONOMICS'),
(19, '학과', 'ElectricalComputerEngineering', 48, '전자공학과', 'ELECTRICALCOMPUTERENGINEERING'),
(20, '단과대', 'Engineering', 9, '공과대학', 'ENGINEERING'),
(21, '학과', 'EnglishLanguageLiterature', 39, '영어영문학과', 'ENGLISHLANGUAGELITERATURE'),
(22, '학과', 'EnvironmentalSafetyEngineering', 58, '환경안전공학과', 'ENVIRONMENTALSAFETYENGINEERING'),
(23, '학과', 'FinancialEngineering', 15, '금융공학과', 'FINANCIALENGINEERING'),
(24, '학과', 'FrenchLanguageLiterature', 24, '불어불문학과', 'FRENCHLANGUAGELITERATURE'),
(25, '학과', 'GlobalBusiness', 14, '글로벌경영학과', 'GLOBALBUSINESS'),
(26, '대학원', 'Graduate', 19, '대학원', 'GRADUATE'),
(27, '학과', 'History', 26, '사학과', 'HISTORY'),
(28, '단과대', 'Humanities', 45, '인문대학', 'HUMANITIES'),
(29, '학과', 'IndustrialEngineering', 29, '산업공학과', 'INDUSTRIALENGINEERING'),
(30, '단과대', 'InformationTechnology', 49, '정보통신대학', 'INFORMATIONTECHNOLOGY'),
(31, '학과', 'IntegrativeSystemsEngineering', 40, '융합시스템공학과', 'INTEGRATIVESYSTEMSENGINEERING'),
(32, '학과', 'IntelligenceSemiconductorEngineering', 51, '지능형반도체공학과', 'INTELLIGENCESEMICONDUCTORENGINEERING'),
(33, '단과대', 'International', 13, '국제학부대학', 'INTERNATIONAL'),
(34, '학과', 'KoreanLanguageLiterature', 12, '국어국문학과', 'KOREANLANGUAGELITERATURE'),
(35, '학과', 'ManagementIntelligence', 5, '경영인텔리전스학과', 'MANAGEMENTINTELLIGENCE'),
(36, '학과', 'MaterialsScienceEngineering', 52, '첨단신소재공학과', 'MATERIALSSCIENCEENGINEERING'),
(37, '학과', 'Mathmatics', 33, '수학과', 'MATHMATICS'),
(38, '학과', 'MechanicalEngineering', 16, '기계공학과', 'MECHANICALENGINEERING'),
(39, '단과대', 'Medicine', 43, '의과대학', 'MEDICINE'),
(40, '학과', 'MilitaryDigitalConvergence', 11, '국방디지털융합학과', 'MILITARYDIGITALCONVERGENCE'),
(41, '단과대', 'NaturalScience', 46, '자연과학대학', 'NATURALSCIENCE'),
(42, '단과대', 'Nursing', 1, '간호대학', 'NURSING'),
(43, '단과대', 'Pharmacy', 38, '약학대학', 'PHARMACY'),
(44, '학과', 'Physics', 22, '물리학과', 'PHYSICS'),
(45, '학과', 'PoliticalScienceDiplomacy', 50, '정치외교학과', 'POLITICALSCIENCEDIPLOMACY'),
(46, '학과', 'Psychology', 35, '심리학과', 'PSYCHOLOGY'),
(47, '학과', 'PublicAdministration', 55, '행정학과', 'PUBLICADMINISTRATION'),
(48, '단과대', 'SocialScience', 27, '사회과학대학', 'SOCIALSCIENCE'),
(49, '학과', 'Sociology', 28, '사회학과', 'SOCIOLOGY'),
(50, '학과', 'Software', 32, '소프트웨어학과', 'SOFTWARE'),
(51, '학과', 'SportsLeisureStudies', 34, '스포츠레저학과', 'SPORTSLEISURESTUDIES'),
(52, '학과', 'TransportationSystemsEngineering', 10, '교통시스템공학과', 'TRANSPORTATIONSYSTEMSENGINEERING'),
(53, '기숙사', 'Dormitory', 17, '기숙사', 'DORMITORY'),
(54, '테스트', 'Test', 53, '테스트', 'TEST'),
(55, '학과', 'AppliedChemistry', 41, '응용화학과', 'APPLIEDCHEMISTRY'),
(56, '학과', 'EconomicPoliticalAndSocialStudies', 7, '경제정치사회융합학부', 'ECONOMICPOLITICALANDSOCIALSTUDIES'),
(57, '학과', 'FrontierSciences', 54, '프런티어과학학부', 'FRONTIERSCIENCES'),
(58, '학과', 'LiberalStudies', 47, '자유전공학부', 'LIBERALSTUDIES');

INSERT INTO club_events (event_id, title, content, writer, created_at, subject, url, likes_count, view_count, type) VALUES
(1, '👉 전공설계 상담 바로가기 👈', '안녕하세요!\n아주대학교 전공설계지원센터 입니다 😄\n대학생이 되기 전 전공을 선택한 학생,\n입학 후 전공을 선택해야 하는 학생,\n새로운 꿈을 꾸며 전공을 바꿔보려는 학생,\n어떤 공부를 해야 할지 고민하는 학생,\n모두 환영합니다!\n지금 U-Chance 학생이력통합시스템에서 전공설계 상담을 신청해 보세요 🤗\n* 상담 관련해 학교 메일 또는 유선 전화(031-219-3121)로 연락을 드릴 예정이니 확인 부탁드립니다.\n* 온라인 상담 신청 시, ZOOM을 통해 상담이 진행됩니다. 상담 전 카메라와 마이크를 준비해 주세요.', '전공설계지원센터', '2026-03-20 17:23:12', '아주대학교-일반', 'https://ajou.ac.kr/kr/ajou/notice.do?mode=view&articleNo=365442', 0, 0, 'AJOUNORMAL'),
(2, '🍩놀심과 함께 대학생활 꿀팁 얻자!!(맛있는 간식도 주는데❤️)', '이번 생엔 대학이 처음이라😥\n이번 생엔 편입은 처음이라😥\n이번 생엔 대학원은 처음이라😥\n아주대는 처음이라...😭\n학교 생활을 어떻게 해야 할지 고민이라면!\n87만 심리전문 유튜버가 말아주는\n대학생활 코칭으로 놀러오세요!\n특강신청하고 맛있는 간식🍩🧃과 함께\n대학생활 꿀팁도 얻어 갑시다!\n많이 신청해주세요.... Please\n담당자가 울고 있어요😭😭\n(글과 포스터를 누르면 신청 페이지로 넘어갑니다!)', '인권센터 학생상담소', '2026-03-20 16:35:12', '아주대학교-일반', 'https://ajou.ac.kr/kr/ajou/notice.do?mode=view&articleNo=365438', 0, 0, 'AJOUNORMAL'),
(3, '2026학년도 1학기 국가근로장학생 추가 모집 안내', '안녕하세요, 장학복지팀입니다.\n2026학년도 1학기 국가근로장학생 추가 모집을 진행합니다.\n근로 장소: 교내 각 부서\n근로 시간: 주 최대 20시간\n지원 자격: 소득분위 8분위 이하 재학생\n신청 기간: 2026.03.25(수) ~ 2026.04.04(금)\n한국장학재단 홈페이지에서 신청하시기 바랍니다.\n문의: 장학복지팀 (031-219-2058)', '장학복지팀', '2026-03-20 10:00:00', '아주대학교-장학', 'https://ajou.ac.kr/kr/ajou/notice.do?mode=view&articleNo=365430', 0, 0, 'AJOUSCHOLARSHIP'),
(4, '2026년 봄 학술제 참가팀 모집 안내', '아주대학교 학술제 운영위원회에서 2026년 봄 학술제 참가팀을 모집합니다.\n주제: 미래 기술과 사회 변화\n참가 자격: 재학생 2인 이상 팀\n접수 기간: 2026.03.22(일) ~ 2026.04.10(목)\n발표일: 2026.05.10(토)\n우수팀에게는 총장상 및 소정의 시상금이 수여됩니다.\n많은 참여 부탁드립니다!\n문의: 학생지원팀 (031-219-2640)', '학생지원팀', '2026-03-19 14:00:00', '아주대학교-일반', 'https://ajou.ac.kr/kr/ajou/notice.do?mode=view&articleNo=365420', 0, 0, 'AJOUNORMAL'),
(5, '중앙도서관 2026년 1학기 정기휴관 및 이용 안내', '안녕하세요, 중앙도서관입니다.\n2026학년도 1학기 정기휴관 일정을 안내드립니다.\n정기휴관일: 매주 일요일 및 공휴일\n야간 열람실 운영: 평일 22:00 ~ 익일 06:00\n좌석 예약: 도서관 앱 또는 홈페이지에서 사전 예약 가능\n1인 1좌석제를 준수해 주시기 바랍니다.\n음식물 반입은 금지되어 있으니 협조 부탁드립니다.\n문의: 중앙도서관 (031-219-2781)', '중앙도서관', '2026-03-18 09:00:00', '아주대학교-일반', 'https://ajou.ac.kr/kr/ajou/notice.do?mode=view&articleNo=365410', 0, 0, 'AJOUNORMAL'),
(6, '2026학년도 교환학생 파견 프로그램 모집 안내', '국제처에서 2026학년도 하반기 교환학생 파견 프로그램 참가자를 모집합니다.\n파견 기간: 2026년 9월 ~ 2027년 2월\n파견 대학: 협정 대학 50개교 (미국, 유럽, 아시아 등)\n지원 자격: 2학년 이상, 평점 3.0 이상, 공인 어학 성적 보유자\n지원 기간: 2026.03.25(수) ~ 2026.04.15(수)\n자세한 사항은 국제처 홈페이지를 참고하세요.\n문의: 국제처 교류협력팀 (031-219-2965)', '국제처', '2026-03-17 11:30:00', '아주대학교-일반', 'https://ajou.ac.kr/kr/ajou/notice.do?mode=view&articleNo=365400', 0, 0, 'AJOUNORMAL');

INSERT INTO club_event_images (url, club_event_id) VALUES
('https://www.ajou.ac.kr/_attach/ajou/editor-image/2026/03/nGslnfDHOYeianJkWndoecRVBL.png', 1),
('https://www.ajou.ac.kr/_attach/ajou/editor-image/2026/03/XoxZNIKeYJfHIakoguhQKDFfMx.png', 1),
('https://www.ajou.ac.kr/_attach/ajou/editor-image/2026/03/cXwtiwBUFuaottcjLJWNtOWouH.png', 1),
('https://www.ajou.ac.kr/_attach/ajou/editor-image/2026/03/PJQhMcWKfojUUOcGfSSODOOwvF.png', 2),
('https://www.ajou.ac.kr/_attach/ajou/editor-image/2026/03/scholarship_notice_2026.png', 3),
('https://www.ajou.ac.kr/_attach/ajou/editor-image/2026/03/academic_festival_2026.png', 4),
('https://www.ajou.ac.kr/_attach/ajou/editor-image/2026/03/library_guide_2026.png', 5),
('https://www.ajou.ac.kr/_attach/ajou/editor-image/2026/03/exchange_student_2026.png', 6);
